### ISSUE TITLE
view have black lines

### ISSUE THREAD

**Issue by wf1992** [ReDetection/RFBConnection#1]
i'm using tightVNC Server ，but i found NPDeskTop demo running in iPad，when the picture changes ,the screen on iPad have black lines! 
Do you saw id,can you tell me how to fix it!

**Comment by ReDetection** [comment]
No I do not undestand which black lines you're talking about. Can you add a picture, please? 
Actually I don't have iPad to check. Did you check if this reproduces on the iPhone?

**Comment by wf1992** [comment]
Sorry , here is the picture . [https://pan.baidu.com/s/1kUPd6nX](url)
And， i run NPDeskTop also have black lines。

**Comment by ReDetection** [comment]
Ah, so this is about frequently updating screen parts.
I've seen this on VNC clients also. Need to make sure received parts to be drawn

**Comment by wf1992** [comment]
yes，i change another func to draw view with his frame buffer ,but it also have black lines. So ,do you have a better plan to deal with this question?

**Comment by wf1992** [comment]
also， i want to know , is his frame buffer have problem or his draw view func have problem? thanks.

**Comment by ReDetection** [comment]
I don't know yet. And no plan also, as I have too few free time now. I hope I'll have some time in summer :(

**Comment by wf1992** [comment]
ok，thanks
